title: 邹欣杰
description: 个人博客
author: 邹欣杰
logo: /assets/img/zxj.png
github: https://github.com/zxinjie
about: Freelance developer

baseurl: "https://zxinjie.github.io/"
url: "https://zxinjie.github.io/"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
